language: generic
sudo: required

git:
  depth: 1

services:
  - postgresql

addons_shortcuts:

  addons_clang38_pg92: &clang38_pg92
    postgresql: '9.2'
    apt:
      sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.8']
      packages: ['clang-3.8', 'postgresql-9.2-postgis-2.3',
                      'python-psycopg2', 'libexpat1-dev', 'libpq-dev', 'libbz2-dev', 'libproj-dev',
                      'lua5.2', 'liblua5.2-dev', 'libluajit-5.1-dev',
                      'libboost1.55-dev', 'libboost-system1.55-dev', 'libboost-filesystem1.55-dev']

  addons_clang60_pg96: &clang60_pg96
    postgresql: '9.6'
    apt:
      update: true
      sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
      packages: ['clang-6.0','postgresql-9.6-postgis-2.3',
                      'python-psycopg2', 'libexpat1-dev', 'libpq-dev', 'libbz2-dev', 'libproj-dev',
                      'lua5.2', 'liblua5.2-dev', 'libluajit-5.1-dev',
                      'libboost1.55-dev', 'libboost-system1.55-dev', 'libboost-filesystem1.55-dev']

  addons_gcc48_pg96: &gcc48_pg96
    postgresql: '9.6'
    apt:
      sources: ["ubuntu-toolchain-r-test"]
      packages: ['g++-4.8','postgresql-9.6-postgis-2.3',
                      'python-psycopg2', 'libexpat1-dev', 'libpq-dev', 'libbz2-dev', 'libproj-dev',
                      'lua5.2', 'liblua5.2-dev', 'libluajit-5.1-dev',
                      'libboost1.55-dev', 'libboost-system1.55-dev', 'libboost-filesystem1.55-dev']


  addons_gcc8_pg96: &gcc8_pg96
    postgresql: '9.6'
    apt:
      sources: ["ubuntu-toolchain-r-test"]
      packages: ['g++-8','postgresql-9.6-postgis-2.3',
                      'python-psycopg2', 'libexpat1-dev', 'libpq-dev', 'libbz2-dev', 'libproj-dev',
                      'lua5.2', 'liblua5.2-dev', 'libluajit-5.1-dev',
                      'libboost1.55-dev', 'libboost-system1.55-dev', 'libboost-filesystem1.55-dev']

# env: T="...."     //  please set an unique test id (T="..")
matrix:
  include:
  # ---- Linux + CLANG ---------------------------
    - os: linux
      compiler: "clang-3.8"
      env: T="clang38_pg92_dbtest" RUNTEST="#Dbtest" LUAJIT_OPTION="OFF"
           CXXFLAGS="-pedantic -Werror"
           CC=clang-3.8 CXX=clang++-3.8
      addons: *clang38_pg92

    - os: linux
      compiler: "clang-6.0"
      env: T="clang60_pg96_asan_dbtest_luajit" RUNTEST="#Dbtest" LUAJIT_OPTION="ON"
           CXXFLAGS="-pedantic -Werror -fsanitize=address,undefined,integer "
           CC=clang-6.0 CXX=clang++-6.0
           ASAN_OPTIONS="verbosity=1:log_threads=1"
           LSAN_OPTIONS="verbosity=1:log_threads=1"
      addons: *clang60_pg96

  # ---- OSX + CLANG ---------------------------

    - os: osx
      compiler: clang
      env: T="osx_clang_NoDB" RUNTEST="-L NoDB" LUAJIT_OPTION="OFF"
           CXXFLAGS="-pedantic -Werror"
      before_install:
        - brew install lua;
      before_script:
        - xml2-config --version
        - proj | head -n1
        - lua -v


  # ---- Linux + GCC ---------------------------
    - os: linux
      compiler: "gcc-4.8"
      env: T="gcc48_pg96_dbtest_luajit"  RUNTEST="#Dbtest" LUAJIT_OPTION="ON"
           CXXFLAGS="-pedantic -Werror"
           CC=gcc-4.8 CXX=g++-4.8
      addons: *gcc48_pg96

    - os: linux
      compiler: gcc-8
      env: T="gcc8_pg96_dbtest_luajit" RUNTEST="#Dbtest" LUAJIT_OPTION="ON"
           CXXFLAGS=" -pedantic -Werror  "
           CC=gcc-8 CXX=g++-8
      addons: *gcc8_pg96


  allow_failures:
    - os: linux
      env: T="clang60_pg96_asan_dbtest_luajit" RUNTEST="#Dbtest" LUAJIT_OPTION="ON"
           CXXFLAGS="-pedantic -Werror -fsanitize=address,undefined,integer "
           CC=clang-6.0 CXX=clang++-6.0
           ASAN_OPTIONS="verbosity=1:log_threads=1"
           LSAN_OPTIONS="verbosity=1:log_threads=1"


before_install:
  - sudo mkdir -p /extra/pg/tablespacetest   # for the database test
  - sudo chown postgres:postgres /extra/pg/tablespacetest
  - dpkg -l | grep -E 'lua|proj|xml|bz2|postgis|zlib|boost|expat'  # checking available versions
before_script:
  - psql -U postgres -c "SELECT version()"
  - psql -U postgres -c "CREATE TABLESPACE tablespacetest LOCATION '/extra/pg/tablespacetest'"
  - psql -U postgres -c "CREATE EXTENSION postgis"
  - psql -U postgres -c "CREATE EXTENSION hstore"
  - psql -U postgres -c "SELECT PostGIS_Full_Version()"
  - $CXX --version
  - xml2-config --version
  - proj | head -n1
  - lua -v
script:
  - mkdir build && cd build
  - cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DWITH_LUAJIT=$LUAJIT_OPTION
  - make -j2
  - echo "Running tests ... "
  - if [[ $RUNTEST ]]; then ctest -VV $RUNTEST; fi
after_failure:
  - # rerun make, but verbosely
    make VERBOSE=1

# end of .travis